# Generated by Django 5.0.3 on 2025-10-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_language_region_remove_country_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='gdp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='neighbors',
            field=models.ManyToManyField(blank=True, to='countries.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='time_zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
