# Generated by Django 5.0.3 on 2025-10-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_country_currency_country_gdp_country_neighbors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='map_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
